export const IMAGES = {
    img0: require('../assets/images/myimg/illustration.png'),
    img1: require('../assets/images/myimg/azzulassets.png'),
    m1: require('../assets/images/myimg/m1.jpg'),
    m2: require('../assets/images/myimg/m2.jpg'),
    m3: require('../assets/images/myimg/m3.jpg'),
    m4: require('../assets/images/myimg/m4.jpg'),
  
    appname : require('../assets/images/appname.jpg'),
    appnamedark : require('../assets/images/appname-dark.jpg'),
    google2 : require('../assets/images/icons/google2.png'),
    facebook : require('../assets/images/icons/facebook.png'),
    Home: require('../assets/images/icons/home.png'),
    Home4: require('../assets/images/icons/home4.png'),
    heart: require('../assets/images/icons/heart.png'),
    mycart: require('../assets/images/icons/shopping2.png'),
    Category: require('../assets/images/icons/document.png'),
    user2: require('../assets/images/icons/user.png'),
    user3: require('../assets/images/icons/user4.png'),
    grid3: require('../assets/images/icons/grid3.png'),
    grid4: require('../assets/images/icons/grid4.png'),
    grid5: require('../assets/images/icons/grid5.png'),
    grid6: require('../assets/images/icons/grid6.png'),
    shose: require('../assets/images/icons/shose.png'),
    ball: require('../assets/images/icons/bell2.png'),
    ball2: require('../assets/images/icons/bell.png'),
    close: require('../assets/images/icons/close.png'),
    check: require('../assets/images/icons/check.png'),
    check2: require('../assets/images/icons/check2.png'),
    check3: require('../assets/images/icons/check3.png'),
    check4: require('../assets/images/icons/check4.png'),
    delete: require('../assets/images/icons/delete.png'),
    Chat: require('../assets/images/icons/Chat.png'),
    Star: require('../assets/images/icons/Star.png'),
    Star4: require('../assets/images/icons/star4.png'),
    wallet: require('../assets/images/icons/wallet.png'),
    wallet2: require('../assets/images/icons/wallet2.png'),
    Location: require('../assets/images/icons/Location.png'),
    Filter: require('../assets/images/icons/Filter.png'),
    Notification: require('../assets/images/icons/Notification.png'),
    search: require('../assets/images/icons/search.png'),
    list: require('../assets/images/icons/list.png'),
    list2: require('../assets/images/icons/list2.png'),
    grid: require('../assets/images/icons/grid.png'),
    arrowup: require('../assets/images/icons/arrowup.png'),
    filter2: require('../assets/images/icons/filter2.png'),
    filter3: require('../assets/images/icons/filter3.png'),
    addtocarticon: require('../assets/images/icons/addcart.png'),
    shop: require('../assets/images/icons/shop.png'),
    Bag: require('../assets/images/icons/Bag.png'),
    plus: require('../assets/images/icons/plus.png'),
    dollar: require('../assets/images/icons/dollar.png'),
    payment: require('../assets/images/icons/payment.png'),
    folder: require('../assets/images/icons/folder.png'),
    bank: require('../assets/images/icons/bank.png'),
    shieldcheck: require('../assets/images/icons/shieldcheck.png'),
    card2: require('../assets/images/icons/card2.png'),
    write: require('../assets/images/icons/write.png'),
    downaeeowsmall: require('../assets/images/icons/downaeeowsmall.png'),
    home: require('../assets/images/icons/home4.png'),
    producta: require('../assets/images/icons/producta.png'),
    components: require('../assets/images/icons/components.png'),
    star: require('../assets/images/icons/star2.png'), 
    heart2: require('../assets/images/icons/heart2.png'), 
    order: require('../assets/images/icons/order.png'), 
    shopping: require('../assets/images/icons/shopping3.png'), 
    chat: require('../assets/images/icons/chat2.png'), 
    logout: require('../assets/images/icons/logout.png'), 
 
    background: require('../assets/images/icons/background.png'), 
    star7: require('../assets/images/icons/star7.png'), 
    leftarrow: require('../assets/images/icons/leftarrow.png'), 
    map: require('../assets/images/icons/map.png'), 
    savecheck: require('../assets/images/icons/save-check.png'), 
    translation: require('../assets/images/icons/translate.png'), 
    transfer: require('../assets/images/icons/transfer.png'), 
    shoppingbag: require('../assets/images/icons/shoppingbag.png'), 
    mobilenotch: require('../assets/images/icons/mobile-notch.png'), 
    marketplacestore: require('../assets/images/icons/marketplace-store.png'), 
    laptopmobile: require('../assets/images/icons/laptop-mobile.png'), 
    gamepad: require('../assets/images/icons/gamepad.png'), 
    couch: require('../assets/images/icons/couch.png'), 
    cameraretro: require('../assets/images/icons/camera-retro.png'), 
    qrscan: require('../assets/images/icons/qr-scan.png'), 
    airfreshener: require('../assets/images/icons/air-freshener.png'), 
    fashion: require('../assets/images/icons/fashion.png'), 




}